### PR TITLE
SOLV 2981: Store credit

### PR DESCRIPTION
**Pull request by dylan-chong**

### CODE REVIEW

**Review by jethro-solve — APPROVED** [review]
Looks good. I'm not 100% sure if store credit should be an adjustment vs a type of payment, but this feels sensible to start with and we can can always change further down the track.

**Comment by dylan-chong** [comment]
Yeah good question, I'd say it depends on whether issuing store credit counts as a refund or not. If it does, then it should be a payment, otherwise, no. That way the revenue still adds up. I'll see if I can look into this

**Comment by dylan-chong** [comment]
So i created an order of $84.50 and "paid" it
Then I refunded all $84.50 and then added in $10 in store credit
We get a return of $84.50, by looking at the total_refunded field (https://shared-00.sandbox.solvedata.app/orders/nz_web/3001089805)
The store credit isn't accounted for in the refund, so we should not create a special payment (remembering that returns are in part a negative payment).
So it is all fine as it is

**Comment by dylan-chong** [comment]
Refunding again, it looks weird

Screenshot 2021-06-24 at 11 15 59 AM

Screenshot 2021-06-24 at 11 21 42 AM

In this screenshot it says

> We refunded NZ$118.50 to Store Credit
> We refunded NZ$108.50 offline.

So the refund and refund-to-store-credit seems like 2 different things

**Comment by dylan-chong** [comment]
Magento is stupid. In the 1st screenshot you have to click Update Totals after updating the Store Credit amount below. But you can't click it unless you change one of the totals above Update Totals

To be honest I'm going to have to take a deeper look at it some other time, but we have more important things going on than fixing having a few returns off. Will merge and take a deeper look later

**Comment by dylan-chong** [comment]
Ticket for later https://solvedata.atlassian.net/browse/SOLV-3110

**Pull request merged**
